<a href="https://colab.research.google.com/github/amitmeel/TensorFlow-Developer-Certificate-in-2021-Zero-to-Mastery/blob/develop/tensorflow_basics_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [5]:
#create tensor wth tf.constant()

scaler = tf.constant(4)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [6]:
## check the number of  dimention of a tensor 
scaler.ndim

0

In [7]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# dimention of vector
vector.ndim

1

In [10]:
# create matrix
matrix = tf.constant([[2,3],
                    [5,65]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 5, 65]], dtype=int32)>

In [11]:
# dimention of matrix
matrix.ndim

2

In [14]:
another_matrix = tf.constant([[10., 5.],
                              [5., 7.],
                              [5,6]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 5.,  7.],
       [ 5.,  6.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [17]:
# create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[14, 15, 16],
                       [17, 45, 56]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[14, 15, 16],
        [17, 45, 56]]], dtype=int32)>

In [18]:
tensor.ndim

3

* scaler: a single number
* vector: a number with direction
* matrix: a 2-dim array of numbers
* tensor: an n-dim array of numbers (where n can be any number, a 0-dimentional tensor is scaler, a 1-dimentional tensor is vector))

## Creating tensor with tf.Variable

In [22]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [23]:
## change one of the elements in the changable_tensor

changable_tensor[0] = 7

TypeError: ignored

In [24]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [25]:
## change in unchangable_tensor
unchangable_tensor[0] = 7

TypeError: ignored

In [26]:
unchangable_tensor[0].assign(7)

AttributeError: ignored

## Creating random tensors

In [30]:
## create two random tensors (but the same)
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [31]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [34]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of elements in a tensor

In [38]:
# shuffle a tensor (valuable for when we want to shuffle your data so the inherent order doesn't affect learning)

not_shuffled = tf.constant([[10, 7],
                            [5, 6],
                            [5,9]])

## shuffle our non-shufflable tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [10,  7],
       [ 5,  9]], dtype=int32)>

In [40]:
## shuffle our non-shufflable tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 5,  9]], dtype=int32)>

In [44]:
## shuffle our non-shufflable tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 5,  9]], dtype=int32)>

In [45]:
## shuffle our non-shufflable tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [10,  7],
       [ 5,  6]], dtype=int32)>

In [46]:
## shuffle our non-shufflable tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [10,  7],
       [ 5,  6]], dtype=int32)>

In [49]:
## shuffle our non-shufflable tensor
tf.random.shuffle(not_shuffled, seed=42) #every time diffrent 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 5,  9]], dtype=int32)>

In [52]:
## shuffle our non-shufflable tensor
tf.random.set_seed(42) ## global level opention random seed
tf.random.shuffle(not_shuffled, seed=42) #local level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 5,  9]], dtype=int32)>

## other ways to make tensor



In [54]:
#create a tensor of all one
tf.ones(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [56]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [57]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [58]:
#3 create a tensor of all zeros
tf.zeros(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

## turn numpy arra into tensors


In [59]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [61]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [62]:
B = tf.convert_to_tensor(numpy_A)

In [63]:
B

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [65]:
c = tf.constant(numpy_A, shape=(2,3,4))

In [67]:
## 2*3*4 =24
c

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

## Getting information from tensors (shape, rank, size)

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:
* **Shape:** The length (number of elements) of each of the dimensions of a tensor.
* **Rank:** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* **Axis** or **Dimension:** A particular dimension of a tensor.
* **Size:** The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the `ndim` attribute. Let's see the rest.

In [77]:
#create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])

In [78]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [79]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [80]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [85]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [86]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing tensors

tensors can be indexed like python

In [87]:
## get first 2 elements of each direction
rank_4_tensor[:2, :2:, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [89]:
# get the first element from each direction from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [95]:
# create a rank 2 tesnor
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]])

In [96]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [97]:
## get the last item of each of row of our rank 2 tesnor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [99]:
#add extra dimention to our rank 2 tensors
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [100]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [101]:
## alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [102]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

## tensor operations

In [103]:
# you cna add values to a tensor using the addition operator

tensor= tf.constant([[2,3],[5,6]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [15, 16]], dtype=int32)>

In [104]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [105]:
# multiplication
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  9],
       [15, 18]], dtype=int32)>

In [106]:
#subtraction
tensor- 15

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-13, -12],
       [-10,  -9]], dtype=int32)>

In [107]:
# we can use th etensorflow builtin as well
tf.multiply(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  9],
       [15, 18]], dtype=int32)>

## matrix multiplication

In [109]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 24],
       [40, 51]], dtype=int32)>

In [110]:
# matrix multiplicaion with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 24],
       [40, 51]], dtype=int32)>

In [111]:
tensor.shape

TensorShape([2, 2])

In [112]:
# tesnor (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[11,12],
                 [13,14],
                 [15,16]])

In [113]:
X@y

InvalidArgumentError: ignored

In [114]:
tf.matmul(X,y)

InvalidArgumentError: ignored

In [115]:
# change the shape of y
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [118]:
# try to matrix multiply by rehsapoed y
X @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [119]:
tf.matmul(X, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [122]:
# try change the shape of X and matrix multiply
tf.matmul(tf.reshape(X, shape=(2,3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 82,  88],
       [199, 214]], dtype=int32)>

In [123]:
# can do the same with transopose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [125]:
# try matrix multiplication with transpose rather than reshape
tf.transpose(X) @ y


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 134],
       [164, 176]], dtype=int32)>

#### dot product (matrix multiplication is also known as do product)

* tf.matmul()
* tf.tensordot()

In [126]:
## # perform the dot product on X and y (X or y to be trnasposed)

In [128]:
tf.tensordot(tf.transpose(X), y)

TypeError: ignored

In [129]:
tf.tensordot(tf.transpose(X), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 134],
       [164, 176]], dtype=int32)>

In [131]:
tf.matmul(X, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 35,  41,  47],
       [ 81,  95, 109],
       [127, 149, 171]], dtype=int32)>

In [132]:
tf.matmul(X, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [135]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(y))

Normal Y:
tf.Tensor(
[[11 12]
 [13 14]
 [15 16]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[11 13 15]
 [12 14 16]], shape=(2, 3), dtype=int32)


### changing the datatype of a tesnor

In [136]:
# create a new tesnor with default datatype (float32)
b= tf.constant([2.3, 5.6])
b.dtype

tf.float32

In [137]:
c = tf.constant([12,2])
c.dtype

tf.int32

In [138]:
# change from float32 to float16 (reduced precision)
b = tf.cast(b, dtype=tf.float16)
b.dtype

tf.float16

In [139]:
c = tf.cast(c, dtype=tf.float16)
c.dtype

tf.float16

### aggregating tensors

In [143]:
d = tf.constant([-3,4])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3,  4], dtype=int32)>

In [144]:
## get the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [149]:
# create a random tensor
e = tf.constant(np.random.randint(0,100, size=50))

In [150]:
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74, 36, 62, 99, 72, 81, 86, 30, 65, 10, 68, 58,  1, 87,  3, 25,  8,
       33, 42, 59, 60, 57, 61, 86, 47, 82, 57, 36,  2, 24, 79, 37, 35, 41,
       72, 96, 24, 60, 30, 77, 13, 94, 61, 56, 95, 24, 65, 87, 41,  9])>

In [151]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [152]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [153]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [154]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2607>

In [156]:
# find variance
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=768>

In [159]:
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.715706>

In [160]:
tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=768.1604>

In [161]:
# find the positional minimum and maximum'


In [163]:
tf.random.set_seed(42)
f = tf.random.uniform(shape=(50,))

In [164]:
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [165]:

#find max value position/indexin tensor
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [167]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [168]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [169]:
#euality check
f[tf.argmax(f)] == tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [170]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

## sqeezing a tensor (removing all singole dimentions)

In [179]:
tf.random.set_seed(43)
g = tf.constant(tf.random.uniform(shape=(50,)), shape=(1,1,1,1,50))

In [180]:
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
           0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
           0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
           0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
           0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
           0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
           0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
           0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
           0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
           0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ]]]]],
      dtype=float32)>

In [181]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [182]:
g_sqeezed = tf.squeeze(g)
g.shape, g_sqeezed.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

In [183]:
g_sqeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

## one hot ending tensors

In [184]:
some_list = [1,2,3,4] # could be red, blue, yellow, green

In [185]:
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [187]:
tf.one_hot(some_list, 4, on_value="on_value", off_value="of_value")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'of_value', b'on_value', b'of_value', b'of_value'],
       [b'of_value', b'of_value', b'on_value', b'of_value'],
       [b'of_value', b'of_value', b'of_value', b'on_value'],
       [b'of_value', b'of_value', b'of_value', b'of_value']], dtype=object)>

In [188]:
h=tf.range(1,10)

In [189]:
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [190]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [191]:
tf.sqrt(h)

InvalidArgumentError: ignored

In [192]:
tf.sqrt(tf.cast(h, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [194]:
tf.math.log(h)

InvalidArgumentError: ignored

In [195]:
tf.math.log(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## tensorflow and numpy compatibility

In [196]:
j = tf.constant(np.array([3,4]))

In [197]:
j

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 4])>

In [198]:
j.numpy()

array([3, 4])

In [199]:
numpy_j = tf.constant(np.array([3.,4.]))
tensor_j = tf.constant([3.,4.])

In [200]:
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

In [201]:
### how to find access to gpu

In [2]:
# memory footprint support libraries/code
# !ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
# !pip install gputil
# !pip install psutil
# !pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]
def printm():
 process = psutil.Process(os.getpid())
 print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
 print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm() 

Gen RAM Free: 12.8 GB  | Proc size: 118.5 MB
GPU RAM Free: 15109MB | Used: 0MB | Util   0% | Total 15109MB


In [5]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [9]:
!/usr/bin/nvidia-smi

Wed Aug 18 12:03:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------